### ISSUE TITLE
Autoscroll is broken

### ISSUE THREAD

**Issue by lesander** [AxTo/GlassChat3#12]

**Comment by Zyiks** [comment]
Just a last fyi from me on this project, autoscroll was working pretty good at one point but your server was too potato to update the hud fast enough so I had to find a workaround. If your current server is no longer potato you just have to find the correct commit which caused autoscroll to work.

The workarounds idea was was to never clear the hud at all, but constantly change the elements on it with settext or whatever. Which means you should not have noticed that the server was potato.

The old implementation cleared the HUD and created all texts again.

I recommend trying to get the workaround running still but if you are shooting to get this stable quick, just check my older commits and find what was working.
